#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="nvim,espanso_mac,karabiner,gitconfig,karabiner"
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
